"""Updated models

Revision ID: 1e07743c5c21
Revises: 7a8cd483f13a
Create Date: 2025-03-04 13:31:31.039022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '1e07743c5c21'
down_revision: Union[str, None] = '7a8cd483f13a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_iot_data_id', table_name='iot_data')
    op.drop_table('iot_data')
    op.alter_column('device_inputs', 'device_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('device_inputs', 'owner_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.add_column('devices', sa.Column('system_id', sa.Integer(), nullable=False))
    op.add_column('devices', sa.Column('status', sa.Boolean(), nullable=True))
    op.alter_column('devices', 'name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.drop_index('ix_devices_name', table_name='devices')
    op.drop_index('ix_devices_unique_id', table_name='devices')
    op.drop_constraint('devices_ibfk_1', 'devices', type_='foreignkey')
    op.create_foreign_key(None, 'devices', 'systems', ['system_id'], ['id'])
    op.drop_column('devices', 'unique_id')
    op.drop_column('devices', 'owner_id')
    op.alter_column('notifications', 'message',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('systems', 'description',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('systems', 'owner_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.add_column('users', sa.Column('name', sa.String(length=100), nullable=False))
    op.drop_index('email', table_name='users')
    op.drop_index('username', table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_column('users', 'hashed_password')
    op.drop_column('users', 'username')
    op.drop_column('users', 'is_admin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_admin', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('username', mysql.VARCHAR(length=50), nullable=False))
    op.add_column('users', sa.Column('hashed_password', mysql.VARCHAR(length=255), nullable=False))
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index('username', 'users', ['username'], unique=True)
    op.create_index('email', 'users', ['email'], unique=True)
    op.drop_column('users', 'name')
    op.alter_column('systems', 'owner_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('systems', 'description',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('notifications', 'message',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)
    op.add_column('devices', sa.Column('owner_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('devices', sa.Column('unique_id', mysql.VARCHAR(length=100), nullable=True))
    op.drop_constraint(None, 'devices', type_='foreignkey')
    op.create_foreign_key('devices_ibfk_1', 'devices', 'users', ['owner_id'], ['id'])
    op.create_index('ix_devices_unique_id', 'devices', ['unique_id'], unique=True)
    op.create_index('ix_devices_name', 'devices', ['name'], unique=False)
    op.alter_column('devices', 'name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.drop_column('devices', 'status')
    op.drop_column('devices', 'system_id')
    op.alter_column('device_inputs', 'owner_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('device_inputs', 'device_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.create_table('iot_data',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('device_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('temperature', mysql.FLOAT(), nullable=False),
    sa.Column('humidity', mysql.FLOAT(), nullable=False),
    sa.Column('timestamp', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name='iot_data_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_iot_data_id', 'iot_data', ['id'], unique=False)
    # ### end Alembic commands ###
